criaCartaoBiologia('Células', 'O que são células?', 'As células são as unidades estruturais e funcionais básicas dos organismos vivos.')
criaCartaoBiologia('Genética', 'O que é o DNA?', 'O DNA é o material genético que contém as instruções necessárias para o desenvolvimento e funcionamento de todos os organismos.')
criaCartaoBiologia('Ecologia', 'O que é um ecossistema?', 'Um ecossistema é uma comunidade de organismos interagindo entre si e com o ambiente em que vivem.')
criaCartaoBiologia('Evolução', 'O que é a seleção natural?', 'A seleção natural é o processo pelo qual características vantajosas se tornam mais comuns em uma população ao longo do tempo.')
criaCartaoBiologia('Botânica', 'O que são plantas?', 'Plantas são organismos autotróficos que realizam fotossíntese para produzir seu alimento.')
criaCartaoBiologia('Zoologia', 'O que caracteriza os animais?', 'Os animais são organismos multicelulares, heterotróficos e que se movem em algum estágio de suas vidas.')
criaCartaoBiologia('Fisiologia', 'O que é homeostase?', 'Homeostase é a capacidade do organismo de manter um ambiente interno estável, independentemente das condições externas.')
criaCartaoBiologia('Microbiologia', 'O que são microrganismos?', 'Microrganismos são organismos microscópicos, como bactérias, vírus e fungos.')
criaCartaoBiologia('Anatomia', 'Qual a função do coração?', 'O coração é um órgão responsável por bombear o sangue por todo o corpo.')
criaCartaoBiologia('Citologia', 'O que é a membrana celular?', 'A membrana celular é uma barreira que envolve a célula, controlando a entrada e saída de substâncias.')
criaCartaoBiologia('Biotecnologia', 'O que é biotecnologia?', 'Biotecnologia é a aplicação de princípios científicos e engenharia para modificar organismos e produtos.')
criaCartaoBiologia('Anatomia', 'Qual a função do sistema respiratory?', 'O sistema respiratório troca gases, permitindo a entrada de oxigênio e a saída de dióxido de carbono.')
criaCartaoBiologia('Fisiologia', 'O que faz o sistema nervoso?', 'O sistema nervoso coordena as respostas do corpo e processa informações sensoriais.')
criaCartaoBiologia('Botânica', 'Qual é a função das folhas?', 'As folhas são responsáveis pela fotossíntese e pela troca gasosa com o ambiente.')
criaCartaoBiologia('Zoologia', 'O que são invertebrados?', 'Invertebrados são animais que não possuem coluna vertebral, como insetos, moluscos e aracnídeos.')
criaCartaoBiologia('Genética', 'O que é um gene?', 'Um gene é uma sequência de DNA que codifica uma proteína ou uma função específica.')
criaCartaoBiologia('Ecologia', 'O que são cadeias alimentares?', 'Cadeias alimentares são representações das interações de alimentação entre diferentes organismos em um ecossistema.')
criaCartaoBiologia('Biologia celular', 'O que são organelas?', 'Organelas são estruturas especializadas dentro da célula, cada uma com funções específicas.')
criaCartaoBiologia('Fisiologia', 'O que é a digestão?', 'A digestão é o processo de quebra dos alimentos em nutrientes que podem ser absorvidos pelo corpo.')
criaCartaoBiologia('Biologia Evolutiva', 'O que é especiação?', 'Especiação é o processo pelo qual novas espécies se formam a partir de uma população ancestral.')
criaCartaoBiologia('Biologia do Desenvolvimento', 'O que é embriogênese?', 'Embriogênese é o processo de desenvolvimento do embrião a partir da fertilização até a formação total do organismo.')
criaCartaoBiologia('Biologia Marinha', 'O que são organismos marinhos?', 'Organismos marinhos são aquelas espécies que vivem em ambientes aquáticos, como peixes, mamíferos marinhos e algas.')
criaCartaoBiologia('Genética', 'O que são alelos?', 'Alelso são as diferentes formas de um gene que podem existir em um locus específico no cromossomo.')
criaCartaoBiologia('Citoquímica', 'O que é a mitose?', 'A mitose é o processo de divisão celular que resulta em duas células-filhas idênticas à célula mãe.')
criaCartaoBiologia('Bioquímica', 'O que são enzimas?', 'Enzimas são proteínas que atuam como catalisadores em reações químicas no organismo.')
criaCartaoBiologia('Fisiologia', 'O que é o sistema imunológico?', 'O sistema imunológico é responsável por proteger o corpo contra patógenos e infecções.')
criaCartaoBiologia('Ecologia', 'O que são espécies endêmicas?', 'Espécies endêmicas são aquelas que são encontradas apenas em um local específico e em nenhum outro lugar do mundo.')
criaCartaoBiologia('Biologia da Conservação', 'O que é a Biodiversidade?', 'Biodiversidade refere-se à variedade de vida em todas as suas formas, incluindo a diversidade genética, de espécies e de ecossistemas.')
criaCartaoBiologia('Zoologia', 'O que são vertebrados?', 'Vertebrados são animais que possuem coluna vertebral, como mamíferos, aves, répteis, anfíbios e peixes.')
criaCartaoBiologia('Histologia', 'O que são tecidos?', 'Tecidos são grupos de células semelhantes que realizam uma função específica.')
criaCartaoBiologia('Biogeografia', 'O que é biogeografia?', 'Biogeografia é o estudo da distribuição de espécies e ecossistemas ao redor do mundo.')
criaCartaoBiologia('Botânica', 'Qual a função das raízes?', 'As raízes absorvem água e nutrientes do solo e fixam as plantas no ambiente.')
criaCartaoBiologia('Fisiologia', 'O que são hormônios?', 'Hormônios são mensageiros químicos que regulam várias funções no corpo, como crescimento e metabolismo.')
criaCartaoBiologia('Engenharia Genética', 'O que é transgenia?', 'Transgenia é o processo de inserir genes de um organismo em outro para trazer características desejáveis.')
criaCartaoBiologia('Epidemiologia', 'O que é uma epidemia?', 'Uma epidemia é uma ocorrência súbita e rápida de uma doença em uma comunidade ou população específica.')
criaCartaoBiologia('Fisiologia', 'O que é o sistema endócrino?', 'O sistema endócrino é um conjunto de glândulas que produzem hormônios para regular várias funções corporais.')
criaCartaoBiologia('Botânica', 'O que é fotossíntese?', 'Fotossíntese é o processo pelo qual as plantas convertem a luz solar em energia química.')
criaCartaoBiologia('Zoologia', 'O que são mamíferos?', 'Mamíferos são animais de sangue quente que possuem glândulas mamárias, pelos e geralmente dão à luz a filhotes.')
criaCartaoBiologia('Biologia Molecular', 'Qual a estrutura do DNA?', 'O DNA tem uma estrutura de hélice dupla composta por nucleotídeos.')
criaCartaoBiologia('Ecologia', 'O que são biomas?', 'Biomas são grandes regiões ecológicas com características climáticas e de vegetação específicas.')
criaCartaoBiologia('Entomologia', 'O que são insetos?', 'Insetos são um grupo de animais invertebrados que possuem três partes do corpo, incluindo antenas e exoesqueleto.')
criaCartaoBiologia('Neurociência', 'Qual a função dos neurônios?', 'Neurônios são células do sistema nervoso que transmitem impulsos elétricos para comunicar informações no corpo.')
criaCartaoBiologia('Imunologia', 'O que são anticorpos?', 'Anticorpos são proteínas produzidas pelo sistema imunológico para identificar e neutralizar patógenos.')
criaCartaoBiologia('Cytologia', 'O que é a meiose?', 'A meiose é um tipo de divisão celular que produz células sexuais com metade do número de cromossomos.')
criaCartaoBiologia('Bioética', 'O que é bioética?', 'Bioética é o estudo das questões éticas que surgem nas ciências biomédicas e na biologia.')
criaCartaoBiologia('Etologia', 'O que é o comportamento animal?', 'O comportamento animal refere-se às ações e reações dos animais em resposta a estímulos do ambiente.')
criaCartaoBiologia('Biomecânica', 'O que é biomecânica?', 'Biomecânica é o estudo das forças e movimentos que agem sobre os organismos vivos.')
criaCartaoBiologia('Fisiologia', 'Qual a função dos rins?', 'Os rins filtram o sangue para remover resíduos e regular equilibro de fluidos e eletrólitos.')
criaCartaoBiologia('Climatologia', 'Como o clima afeta a biodiversidade?', 'O clima influencia a distribuição de espécies e a dinâmica dos ecossistemas.')
criaCartaoBiologia('Fisiologia', 'O que é a Respiração celular?', 'Respiração celular é o processo pelo qual as células convertem glicose e oxigênio em energia.');
